# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJOb!
    - bash: echo $(PipelineLevelVariable)
  - job: secondJob
    steps:
    - bash: echo Build secondJOb!
- stage: DevDeploy
  dependsOn: Build
  variables:
    environment: Dev
  jobs:
  - job: FirstJob
    steps:
    - bash: echo ${environment} FirstJOb!
  - job: secondJob
    steps:
    - bash: echo ${environment} secondJOb!
- stage: QADeploy
  dependsOn: Build
  variables:
    environment: QA
  jobs:
  - job: FirstJob
    steps:
    - bash: echo ${environment} FirstJOb!
  - job: secondJob
    steps:
    - bash: echo ${environment} secondJOb!
- stage: PreprodDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  variables:
    environment: Preprod
  jobs:
  - job: FirstJob
    steps:
    - bash: echo ${environment} FirstJOb!
  - job: secondJob
    steps:
    - bash: echo ${environment} secondJOb!
- stage: ProdDeploy
  dependsOn: PreprodDeploy
  variables:
    environment: Prod
  jobs:
  - job: FirstJob
    steps:
    - bash: echo ${environment} FirstJOb!
  - job: secondJob
    steps:
    - bash: echo ${environment} secondJOb!