# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: FirstJob
  steps:
  - script: echo Hare Krishna Hare Ram!!!
- job: Secondjob
  dependsOn: Firstjob
  steps:
  - script: echo Shree Radhe Shyam!!!
- job: Thirdjob
  dependsOn: Secondjob
  steps:
  - script: echo Shree Sita Ram!!!